run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - goconst
    - goimports
    - misspell
    - revive
    - unconvert
    - unused

linters-settings:
  misspell:
    locale: US

issues:
  exclude-dirs:
    - .github
    - web
